<?php

// This file contains the current being tracked configurations.

$tracked = array (
  'field_validation_rule.body_min_words' => '697e1ea8c3ae4d5891df0008ae2b43f133fcbe29',
  'field_validation_rule.ether_regex' => 'babe6cdb0ae1e60b75d051de82df045ca5b730fa',
  'field_validation_rule.eth_address_length' => 'db3c69f91132ee7f3db84675e4c85a603ade3368',
  'field_validation_rule.unique_value' => '7df048310d12812bbc2fe555bb21db4e49051381',
);


// The following modules are required to run the configurations of this file.

$modules = array(
  'ctools',
  'field_validation',
);
